create table null_table(id int not null, num int null, price float not null, birthday date null);
create table null_table2(id int not null, num int null, price float not null, birthday date null);
create index index_num on null_table(num);
insert into null_table values (1, 18, 10.0, '2020-01-01');
insert into null_table values (2, null, 20.0, '2010-01-11');
insert into null_table values (3, 12, 30.0, null);
insert into null_table values (4, 15, 30.0, '2021-01-31');
insert into null_table2 values (1, 18, 30.0, '2021-01-31');
insert into null_table2 values (2, null, 40.0, null);
insert into null_table values (5, 15, null, '2021-01-31');
insert into null_table values (null, 15, 30.0, '2021-01-31');
select * from null_table;
select * from null_table where 1 is null;
select * from null_table where 1 is not null;
select * from null_table where null is null;
select * from null_table where null is not null;
select * from null_table where num is null;
select * from null_table where num is not null;
select * from null_table where num = null;
select * from null_table where null = num;
select * from null_table where num <> null;
select null_table.num,null_table2.num,null_table.birthday from null_table,null_table2 where null_table.num=null_table2.num;
select count(*) from null_table;
select count(price) from null_table;
select count(birthday) from null_table;
select avg(num) from null_table;
create table null_table3(id int not null, num int null);
insert into null_table3 values (1, null);
insert into null_table3 values (2, null);
select count(num) from null_table3;
select min(num) from null_table3;
select max(num) from null_table3;
select avg(num) from null_table3;
exit;
